application: chugchanga-poll
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  login: required
- url: /profile/
  script: main.py
  login: required
- url: /ajax/
  script: main.py
  login: required
- url: /results/
  script: main.py
- url: /ballot/.*
  script: main.py
- url: /canon/.*
  script: main.py
- url: /static
  static_dir: static
